### ISSUE TITLE
deploy to github pages?

### ISSUE THREAD

**Issue by pietroppeter** [incubated-geek-cc/HTML5-Image-Display#1]
hi, thanks for this, very nice repo and article!

In case you are interested to indulge lazy folks like me, if you activate pages (directly from branch, branch main) you get for free a deployed version of this (and you could add a link easily from settings or adding it in the readme). I wanted to play with it without cloning (I am that lazy!) and the fastest way was actually to fork and activating pages myself: https://pietroppeter.github.io/HTML5-Image-Display/ :)

have a great day!

**Comment by incubated-geek-cc** [comment]
So sorry for the delayed response! Thank you for the kind words (: I'll definitely check it out soon and implement. Hope you're well :D

**Comment by pietroppeter** [comment]
No problem 😉. If you have questions feel free to ask, it is really just a couple of setup steps in the repo (does not need to commit anything).
